### ISSUE TITLE
"No enumerators available" when running in docker container

### ISSUE THREAD

**Issue by wuujiann** [rr-/screeninfo#22]
When I call get_monitors() from inside a docker container, I received the following error.
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/screeninfo/screeninfo.py", line 29, in get_monitors
    raise ScreenInfoError("No enumerators available")
screeninfo.common.ScreenInfoError: No enumerators available
```
**Steps to reproduce the problem**
Environment: Ubuntu 18.04
```
$ docker run -it --rm python:3 bash
root@5611d6f56e39:/# pip install screeninfo
root@5611d6f56e39:/# python
>>> from screeninfo import get_monitors
>>> m = get_monitors()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/screeninfo/screeninfo.py", line 29, in get_monitors
    raise ScreenInfoError("No enumerators available")
screeninfo.common.ScreenInfoError: No enumerators available
```
No errors if run from Ubuntu shell.

**Comment by rr-** [comment]
Well docker containers don't have a graphical environment at all so what else would you expect?

**Comment by wuujiann** [comment]
Thanks for  your prompt reply.
Hm.... If docker containers don't have GUI environment, I shouldn't be able to run any GUI apps inside the docker.  However, I was to able to run a simple PySimpleGUI app from inside the docker as follows:
1. Run python container:
```
XSOCK=/tmp/.X11-unix
XAUTH=/tmp/.docker.xauth
xauth nlist $DISPLAY | sed -e 's/^..../ffff/' | xauth -f $XAUTH nmerge -
chmod 777 $XAUTH
docker run --rm -ti --privileged -e DISPLAY=$DISPLAY \
  -v $XSOCK:$XSOCK -v $XAUTH:$XAUTH \
  --net host -e XAUTHORITY=$XAUTH python:3 bash
```
At this point, we should be inside a python container's bash shell.

2. Install PySimpleGUI
`# pip install PySimpleGUI`

3. Run python, and run simple GUI using PySimpleGUI:
```
# python
>>> import PySimpleGUI as sg
>>> win=sg.Window('Hello', [[sg.Text('Hello World!')]]).Finalize()
```
This will popup a "Hello World" GUI window.

4. Query screen dimension from PySimpleGUI gives me the aggregate resolution of both my screens (I have dual screen: 1920x1080.  But PySimpleGUI gives me 3840x1080. 
```
>>> win.GetScreenDimensions()
(3840, 1080)
```

Somehow, PySimpleGUI manages to figure out the total dimension of both my screens.

**Comment by rr-** [comment]
I recently fixed some bugs related to DRM, please let me know if the issue persists

**Comment by rr-** [comment]
Thanks

**Comment by illegalPointer** [comment]
Hello, 

I'm having the same problem, the xhost fix seems to fail for me. I've tested this in a couple of computers to no avail.

`$ xhost +local:docker; docker run --rm -ti --net=host --env="DISPLAY" -h screeninfo-test --volume="$HOME/.Xauthority:/root/.Xauthority:rw" python:3 bash
non-network local connections being added to access control list
root@screeninfo-test:/# pip install screeninfo; python
Collecting screeninfo
  Downloading screeninfo-0.8.1-py3-none-any.whl.metadata (2.9 kB)
Downloading screeninfo-0.8.1-py3-none-any.whl (12 kB)
Installing collected packages: screeninfo
Successfully installed screeninfo-0.8.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Python 3.12.3 (main, Apr 24 2024, 11:17:35) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from screeninfo import get_monitors
>>> m = get_monitors()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.12/site-packages/screeninfo/screeninfo.py", line 32, in get_monitors
    raise ScreenInfoError("No enumerators available")
screeninfo.common.ScreenInfoError: No enumerators available
>>> 
`
