### ISSUE TITLE
Invalid syntax error on OSX with Python 3.5

### ISSUE THREAD

**Issue by vik748** [rr-/screeninfo#37]
When I try using the latest version, I get the following error.  This error shows up all the way back to version 0.3.1 :

```
  File "/Users/vik748/anaconda3/envs/mb_pc_env/lib/python3.5/site-packages/screeninfo/__init__.py", line 1, in <module>
    from .common import Enumerator, Monitor
  File "/Users/vik748/anaconda3/envs/mb_pc_env/lib/python3.5/site-packages/screeninfo/common.py", line 10
    x: int
     ^
SyntaxError: invalid syntax
```

**Comment by rr-** [comment]
Please update python to a more modern version. Latest stable version is 3.8. Python 3.5 will become unsupported in 4 months (2020-09-13)

**Comment by vik748** [comment]
I was using Python 3.5 since everything worked just right.  On updating to Python 3.7 I run into the following:
```
Traceback (most recent call last):
  File "./calculate_corrected_lat_lon_heading.py", line 631, in <module>
    gc = GridCreator(3, 4)
  File "/Users/vik748/multibeam_pointcloud_correction/matplotgrid.py", line 46, in __init__
    cols, rows, monitor_start
  File "/Users/vik748/multibeam_pointcloud_correction/matplotgrid.py", line 94, in validate_inputs
    monitors = get_monitors()
  File "/Users/vik748/anaconda3/envs/mb_pc_env/lib/python3.7/site-packages/screeninfo/screeninfo.py", line 37, in get_monitors
    raise ScreenInfoError("No enumerators available")
screeninfo.common.ScreenInfoError: No enumerators available
```

**Comment by alexadkins** [comment]
I am getting the same issue using Python 3.7.3 and OSX 10.15.5.
```
Traceback (most recent call last):
  File "/usr/local/bin/remouse", line 8, in <module>
    sys.exit(main())
  File "/Library/Python/3.7/site-packages/remarkable_mouse/remarkable_mouse.py", line 119, in main
    read_tablet(args, remote_device)
  File "/Library/Python/3.7/site-packages/remarkable_mouse/pynput.py", line 70, in read_tablet
    monitor = get_monitors()[args.monitor]
  File "/Library/Python/3.7/site-packages/screeninfo/screeninfo.py", line 37, in get_monitors
    raise ScreenInfoError("No enumerators available")
screeninfo.common.ScreenInfoError: No enumerators available
```

**Comment by rr-** [comment]
These are unrelated issues.
