### ISSUE TITLE
customdisplayprofiles current-path not work

### ISSUE THREAD

**Issue by carlosfernandezcabrero** [rr-/screeninfo#64]
Hi,

When i execute this code in python, the program return this message:

Python Code

```python
colorProfilePath = subprocess.check_output("./customdisplayprofiles current-path", shell=True)
```

Error

```zsh
/bin/sh: ./customdisplayprofiles: No such file or directory
Traceback (most recent call last):
  File "/Users/carlosfernandezcabrero/Desktop/useful-scripts/monitors-resolution.py", line 9, in <module>
    colorProfilePath = subprocess.check_output("./customdisplayprofiles current-path", shell=True)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command './customdisplayprofiles current-path' returned non-zero exit status 127.
```

Operating System: macOS
Operating System Version: macOS Monterey 12.1
Python Version: 3.9.9
Package Version: 0.8

Regards thank you very much

**Comment by rr-** [comment]
I don't think this problem is related to this project.

**Comment by carlosfernandezcabrero** [comment]
I resolve this issue, i make the script with node and javascript, you can close this issue.

Regards thank you very much
