### ISSUE TITLE
Exception on Raspberry Pi 4

### ISSUE THREAD

**Issue by ThisLimn0** [rr-/screeninfo#67]
Any chance to support the Raspberry 4? 

a common way to check for screen resolution on bullseye is to run fbset -s in the command line. But there i don't get the manufacturer of the screen and other info. 

```pi@raspberrypi:~/ $ python3
Python 3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from screeninfo import get_monitors
>>> get_monitors()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/.local/lib/python3.9/site-packages/screeninfo/screeninfo.py", line 32, in get_monitors
    raise ScreenInfoError("No enumerators available")
screeninfo.common.ScreenInfoError: No enumerators available
>>> 
```

**Comment by rkiss-technoorg** [comment]
I think my pr will solve this issue (#68)
